### ISSUE TITLE
Requisitos funcionales y diagrama de casos de uso

### ISSUE THREAD

**Issue by KarManiatic** [ISO2-C01-2022-2023/Pilgrimfy#1]
Generar una primera versión de los requisitos funcionales y de sus correspondientes casos de uso. Añadir a esto el diagrama de casos de uso. 

- [x] Documento de requisitos funcionales
- [x] Diagramas de casos de uso

**Comment by GuillermoSantosMolero** [comment]
Primer commit a la rama main, en el que están los casos de uso
